### ISSUE TITLE
ADD lazy loading

### ISSUE THREAD

**Issue by allanlaal** [CarlosAMolina/workWithUrls#1]
please add Lazy Loading:

A:
 loading the next tab after user specified time 

B:
even better: keeping 2 (configurable) loaded at all times and loading another one when the 1st is closed

**Comment by CarlosAMolina** [comment]
Hello Allan,

Thank you for your comment. The Lazy Loading is now available, commit 1e844fc93391d602263965b26af974e7fa4a1e40.

You can set the desired waiting time. The option "B" (keeping 2 (configurable) loaded...) has not been implemented, but I hope option's A implementation covers yours needs.

Kinds regards,
Carlos.
